### ISSUE TITLE
hashlib sha512 doesn't work at all.

### ISSUE THREAD

**Issue by Jaxkr** [replit/jsrepl#69]
import hashlib
data = "hello world"
print hashlib.sha512(data).hexdigest()

On jsrepl Python this returns 98da40428560000006dafbd2aa000000421f6470bc0000008fa6e14611000000bb7abd4f6ac00000ec04e49ad2000000563afc5724000000761fdda95c000000
On system Python this returns 309ecc489c12d6eb4cc40f50c902f2b4d0ed77ee511a7c7a9bcd3ca86d4cd86f989dd35bc5ff499670da34255b45b0cfd830e81f605dcf7dc5542e93ae9cd76f
On another hashing utility (http://hash.online-convert.com/sha512-generator) this returns
309ecc489c12d6eb4cc40f50c902f2b4d0ed77ee511a7c7a9bcd3ca86d4cd86f989dd35bc5ff499670da34255b45b0cfd830e81f605dcf7dc5542e93ae9cd76f
On yet another hashing utility (http://www.miniwebtool.com/sha512-hash-generator/) this return
309ecc489c12d6eb4cc40f50c902f2b4d0ed77ee511a7c7a9bcd3ca86d4cd86f989dd35bc5ff499670da34255b45b0cfd830e81f605dcf7dc5542e93ae9cd76f

I've decided that jsrepl's hashlib is at fault.
However, your struct library works great! Keep that up!

**Comment by amasad** [comment]
We added Python 3 and this works correctly on it http://repl.it/cBo
You can use it on your project or website via our API: http://repl.it/api
