### ISSUE TITLE
PHP Language Support

### ISSUE THREAD

**Issue by enqiang** [replit/jsrepl#79]
Why PHP is not supported in jsrepl ？
Is there any plan to add PHP in the future？
And I have found this seems like jsrepl,  https://github.com/niklasvh/php.js
Jsrepl is so great and useful , so it is earnestly hoped that you'll add PHP language...
Thanks a lot.

**Comment by amasad** [comment]
Added php http://repl.it/languages/PHP
Did it on the server though. You can use through our API: http://repl.it/api
